id_columns: {}
name_column:
  '2': 'Unnamed: 2'
value_columns: {}
worksheet: Kreisfreie_Städte_u._Landkreise
manual_mappings:
- input_ids: {}
  input_name: Burgenlandkreis
  geodata_id: DEE08
  geodata_name: Burgenland (DE)
geodata_level: NUTS 3
geodata_year: '2013'
