id_columns:
  '0': Kreisfreie Städte und Landkreise nach Fläche, Bevölkerung und Bevölkerungsdichte
    am 31.12.2024 (Jahr)
  '2': 'Unnamed: 2'
name_column:
  '1': 'Unnamed: 1'
value_columns: {}
worksheet: Kreisfreie Städte u. Landkreise
geodata_level: NUTS 3
geodata_year: '2024'
