id_columns: {}
name_column:
  '1': 'Unnamed: 1'
value_columns: {}
worksheet: 11111-0002
manual_mappings:
- input_ids: {}
  input_name: Sankt Wendel, Landkreis
  geodata_id: DEC06
  geodata_name: St. Wendel
geodata_level: NUTS 3
geodata_year: '2024'
