id_columns:
  '0': 'Betreute Kinder nach Art der Kindertagesbetreuung - Stichtage - regionale
    Tiefe: Kreise und krfr. Städte (bis 2010)'
name_column:
  '1': 'Unnamed: 1'
value_columns: {}
worksheet: 22543-01-01-4
geodata_level: NUTS 3
geodata_year: '2003'
