id_columns:
  '0': 'Auszug ausgewählter Merkmale aus dem Gemeindeverzeichnis '
  '3': 'Unnamed: 3'
name_column:
  '2': 'Unnamed: 2'
value_columns: {}
worksheet: Kreisfreie_Städte_u._Landkreise
geodata_level: NUTS 3
geodata_year: '2013'
