id_columns: {}
name_column:
  '2': Name
value_columns: {}
worksheet: Tabelle1
manual_mappings:
- input_ids: {}
  input_name: Neustadt an der Aisch-Bad Winsheim
  geodata_id: DE25A
  geodata_name: Neustadt a. d. Aisch-Bad Windsheim
- input_ids: {}
  input_name: Leipzig, Stadt
  geodata_id: DED51
  geodata_name: Leipzig, Kreisfreie Stadt
geodata_level: NUTS 3
geodata_year: '2024'
