id_columns: {}
name_column:
  '0': name
value_columns: {}
manual_mappings:
- input_ids: {}
  input_name: Weiden in der Oberpfalz
  geodata_id: DE233
  geodata_name: Weiden i. d. Opf, Kreisfreie Stadt
geodata_level: NUTS 3
geodata_year: '2024'
