id_columns: {}
name_column:
  '1': Bevölkerungsdichte (EW je qkm)
value_columns: {}
manual_mappings:
- input_ids: {}
  input_name: Oldenburg (Oldb)
  geodata_id: DE943
  geodata_name: Oldenburg (Oldenburg), Kreisfreie Stadt
- input_ids: {}
  input_name: Rostock
  geodata_id: DE803
  geodata_name: Rostock, Kreisfreie Stadt
geodata_level: NUTS 3
geodata_year: '2024'
